### ISSUE TITLE
signer module using SR keys

### ISSUE THREAD

**Issue by xmonader** [codescalers/tfgrid-sdk-dart#2]
Create a module for SR keys functionality into the Dart project to facilitate signing processes required for communication with the Threefold Grid.

- Implement SR key generation and management in Dart.
- Develop signing functions that utilize SR keys for security.
- Tests

**Comment by AlaaElattar** [comment]
### Work Completed:
The pr is ready for review. But it's done with sr keys and it's not supported in the available library.

**Comment by AlaaElattar** [comment]
### Work Completed:
- Both `sr25519` and `ed25519` are supported now.
- pr merged.
