### ISSUE TITLE
Add Twins Module in graphql client

### ISSUE THREAD

**Issue by AlaaElattar** [codescalers/tfgrid-sdk-dart#29]

**Comment by mariammahrous23** [comment]
### Daily Update 22/7
- Added Twins Model 
- Implemented GetTwinById ( To be tested)

**Comment by mariammahrous23** [comment]
### Daily Update 30/7
- Refactored Twin model 
- Implemented both Twins and TwinConnections

**Comment by mariammahrous23** [comment]
### Daily Update 31/7
- Refactored Twin and twinconnections code

**Comment by mariammahrous23** [comment]
### Daily Update 5/7
- Updated error messages 
- Refactored the code after allBoolenFalse
