### ISSUE TITLE
Add Contracts module in graphql client

### ISSUE THREAD

**Issue by AlaaElattar** [codescalers/tfgrid-sdk-dart#32]
- The following functions should be covered : `listNameContractsByTwinId`,`listNodeContractsByTwinId`, `listRentContractsByTwinId`,  `getConsumptionForNameContracts` , `getConsumptionForNodeContracts`, `getConsumptionForRentContracts`

**Comment by Basem1166** [comment]
- added listNameContractsByTwinId,listNodeContractsByTwinId, listRentContractsByTwinId

**Comment by Basem1166** [comment]
- added listBillReportsByContractId
