### ISSUE TITLE
Add Nodes module in graphql client

### ISSUE THREAD

**Issue by AlaaElattar** [codescalers/tfgrid-sdk-dart#33]
- The following functions should be covered: `nodes`, `nodesConnection`, `nodeResourcesTotals`, `nodeResourcesTotalsConnection`.

**Comment by mariammahrous23** [comment]
- Implemented most of the node query (tfchain_GraphQl) missing (LocationWhere query , PowerWhere query , Interface where query , PublicConfig where query , NodeResourcesTotal where query)

**Comment by mariammahrous23** [comment]
- Finished Implementing both Nodes and NodeResourcesTotals

**Comment by mariammahrous23** [comment]
### Daily Update 5/7
- Added nodesConnection 
- Started Implementing nodeResourcesTotalsConnection

**Comment by mariammahrous23** [comment]
### Daily Update 6/8
- Finished implementing nodeResourcesTotalConnection  
- refactored the code

**Comment by mariammahrous23** [comment]
### Daily Update 8/8
- Refactored the code
