### ISSUE TITLE
tfchain module

### ISSUE THREAD

**Issue by xmonader** [codescalers/tfgrid-sdk-dart#4]
Develop Dart functionalities to interact with tfchain, including executing extrinsics and handling transactions on the blockchain and queries

- Implement a Dart library for interacting with the tfchain blockchain.
- Include methods for executing extrinsics and querying blockchain data.
- Test the integration against devnet tfchain .

**Comment by AlaaElattar** [comment]
### Work in Progress (WIP):
Started working on tfchain client against devnet.

**Comment by AlaaElattar** [comment]
### Work Completed:
- I've implemented `QueryClient` in tfchain package will all modules except `dao` module and `listenToMintCompleted` function in QueryBridge module.

### Work in Progress (WIP):
- Working on Full Client that perform extrinsics.

**Comment by AlaaElattar** [comment]
### Work In Progress:
- Decoding done for extrinsics in `finalized` and `inBlock` events.
- working on converting the decoded map to json to check if the extrinsic pass of fail.

**Comment by AhmedHanafy725** [comment]
client is added to the main branch
